[package]
name = "offset-dumper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced-x86 = "1.14.0"
anyhow = "1.0.43"
regex = "1.5.4"
thiserror = "1.0.28"
log = "0.4.14"
either = "1.6.1"